#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "MW_PX4_TaskControl.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE PX4 Cube Orange
#define MW_EXTMODEPROTOCOLINFO_XCPONSERIAL_HOSTINTERFACE Simulink
#define MW_EXTMODEPROTOCOLINFO_XCPONSERIAL_LOGGINGBUFFERAUTO 1
#define MW_EXTMODEPROTOCOLINFO_XCPONSERIAL_LOGGINGBUFFERSIZE 1024
#define MW_EXTMODEPROTOCOLINFO_XCPONSERIAL_LOGGINGBUFFERNUM 3
#define MW_EXTMODEPROTOCOLINFO_XCPONSERIAL_MAXCONTIGSAMPLES 10
#define MW_CONNECTIONINFO_XCPONSERIAL_BAUDRATE codertarget.pixhawk.internal.getExternalModeBaudrate(hCS);
#define MW_CONNECTIONINFO_XCPONSERIAL_COMPORT codertarget.pixhawk.internal.getExternalSerialPortName(hCS);
#define MW_CONNECTIONINFO_XCPONSERIAL_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION XCP on Serial
#define MW_RTOS NuttX
#define MW_RTOSBASERATETASKPRIORITY 250
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 0
#define MW_CMAKECONFIG cubepilot_cubeorange_fixedwing
#define MW_CHANGECMAKECONFIG 48
#define MW_AUTOMATIC_SERIAL_SCAN 1
#define MW_COM_UPLOAD_STORAGE 
#define MW_NUTTX_SERIAL_PORT 
#define MW_ENABLE_HITL 0
#define MW_SIMULATOR 0
#define MW_CONNECTEDIOSERIALPORT /dev/ttyACM0
#define MW_CONNECTEDIOSERIALPORT_CHECKBOX 1
#define MW_CONNECTEDIOHOSTCOMPORT 
#define MW_SIMULINKIO_MODELTRANSPORTDATAFCN px4.internal.ConnectedIO.getConfigsetInfo
#define MW_SIMULINKIO_SERVERDEPLOYFCN px4.internal.ConnectedIO.buildAndDeployPX4IOServer
#define MW_CLOCKING_CPUCLOCKRATEMHZ 400
#define MW_EXTSERIALPORT 0
#define MW_EXTMODESERIALPORT_CHECKBOX 1
#define MW_EXTMODEHOSTCOMPORT 
#define MW_PILSERIALPORT /dev/ttyACM0
#define MW_PILSERIALPORT_CHECKBOX 1
#define MW_PILHOSTCOMPORT 
#define MW_I2C_BUS1SPEEDKHZ_INDEX 0
#define MW_I2C_BUS2SPEEDKHZ_INDEX 0
#define MW_I2C_BUS1SPEEDKHZ 100
#define MW_I2C_BUS2SPEEDKHZ 100
#define MW_CAN_PORTINDEX 0
#define MW_CAN_BAUDRATE_INDEX 2
#define MW_CAN_BAUDRATE 500000
#define MW_CAN_TESTMODE 0
#define MW_ENABLEMAVLINKCHECKBOX 1
#define MW_TTYACM0_BAUDRATE 27
#define MW_TTYACM0_PARITY 0
#define MW_TTYACM0_STOPBIT 0
#define MW_TTYACM0_PORTMAP 48
#define MW_TTYS0_BAUDRATE 27
#define MW_TTYS0_PARITY 0
#define MW_TTYS0_STOPBIT 0
#define MW_TTYS0_PORTMAP 48
#define MW_TTYS0HWFLOWCONTROL_CHECKBOX 0
#define MW_TTYS1_BAUDRATE 27
#define MW_TTYS1_PARITY 0
#define MW_TTYS1_STOPBIT 0
#define MW_TTYS1_PORTMAP 48
#define MW_TTYS1HWFLOWCONTROL_CHECKBOX 0
#define MW_TTYS2_BAUDRATE 27
#define MW_TTYS2_PARITY 0
#define MW_TTYS2_STOPBIT 0
#define MW_TTYS2_PORTMAP 48
#define MW_TTYS2HWFLOWCONTROL_CHECKBOX 0
#define MW_TTYS5_BAUDRATE 27
#define MW_TTYS5_PARITY 0
#define MW_TTYS5_STOPBIT 0
#define MW_TTYS5_PORTMAP 48
#define MW_HRT_CONSTRAINT 0
#define MW_SEM_WATERMARK 20
#define MW_IOBLOCKSMODE connected
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
